apiVersion: v1
kind: Service
metadata:
  name: iot-sensor-api-service
spec:
  selector:
    app: iot-sensor-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
